In [6]:
"""Задание 1.3.1 Р/т №2"""
import numpy as np

array = np.zeros((10,10))
array[::2, ::2] = 1
array[1::2, 1::2] = 1
print(array)

[[1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


In [9]:
"""Задание 1.3.2 Р/т №2"""
import numpy as np

array = np.zeros((5, 5))
array[::, ::] = np.arange(0, 5)
print(array)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [10]:
"""Задание 1.3.3 Р/т №2"""
import numpy as np

array = np.random.random((3, 3, 3))
print(array)

[[[0.42857248 0.41996726 0.61864638]
  [0.51677587 0.85608067 0.40513955]
  [0.10267609 0.42202458 0.98272868]]

 [[0.61193113 0.14612973 0.12857492]
  [0.66331751 0.49679069 0.74023934]
  [0.86611741 0.7761596  0.97241135]]

 [[0.07831752 0.76392549 0.69915404]
  [0.99416972 0.02096552 0.65550998]
  [0.94914803 0.5320406  0.5024433 ]]]


In [12]:
"""Задание 1.3.4 Р/т №2"""
import numpy as np

array = np.zeros((5, 5))
array[0, ::] = 1
array[::, 0] = 1
array[::, -1] = 1
array[-1, ::] = 1
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
"""Задание 1.3.5 Р/т №2"""
import numpy as np

array = np.array([3, 5, 2, 7, 1, 4, 6])
print(np.sort(array)[::-1])

[7 6 5 4 3 2 1]


In [16]:
"""Задание 1.3.6 Р/т №2"""
import numpy as np

array = np.zeros((5, 4))

print(array.shape, '\n',array.size, '\n',array.ndim)

(5, 4) 
 20 
 2


In [2]:
"""Задание 2.3.1 Р/т №2"""
import pandas as pd
import numpy as np

a = pd.Series([1, 2, 3, 4, 5])
b = pd.Series([4, 3, 2, 1, 0])

squared_diff = (a - b) ** 2
sum_squared_diff = np.sum(squared_diff)
distance = np.sqrt(sum_squared_diff)

print(distance)

6.708203932499369


In [14]:
"""Задание 2.3.2 Р/т №2"""
import pandas as pd
import numpy as np

# url = 'https://github.com/akmand/datasets/blob/main/abolone.csv'

dataframe = pd.read_csv("./abolone.csv", sep=',', nrows=10)

dataframe.head(5)

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   

   Viscera weight  Shell weight  Rings  
0          0.1010         0.150     15  
1          0.0485         0.070      7  
2          0.1415         0.210      9  
3          0.1140         0.155     10  
4          0.0395         0.055      7

In [23]:
"""Задание 2.3.3 Р/т №2"""
import pandas as pd
import numpy as np

# url = 'https://github.com/akmand/datasets/blob/main/abolone.csv'

dataframe = pd.read_csv("./abolone.csv", sep=',', nrows=10)

dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe

dataframe.iloc[3:5]

dataframe[dataframe['Gender'] == 'M'].head(2)

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   

   Viscera weight  Shell weight  Rings  
0          0.1010          0.15     15  
1          0.0485          0.07      7

In [26]:
"""Задание 3.3.2 Р/т №2"""
import pandas as pd
from sklearn import preprocessing

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'

dataframe = pd.read_csv(url)
dataframe.head(5)

minmax_scaler = preprocessing.MinMaxScaler()
standard_scaler = preprocessing.StandardScaler()

dataframe['sepal_length_cm_normalized'] = minmax_scaler.fit_transform(dataframe[['sepal_length_cm']])

dataframe['sepal_width_cm_normalized'] = standard_scaler.fit_transform(dataframe[['sepal_width_cm']])

dataframe.head(5)

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species  \
0              5.1             3.5              1.4             0.2  setosa   
1              4.9             3.0              1.4             0.2  setosa   
2              4.7             3.2              1.3             0.2  setosa   
3              4.6             3.1              1.5             0.2  setosa   
4              5.0             3.6              1.4             0.2  setosa   

   sepal_length_cm_normalized  sepal_width_cm_normalized  
0                    0.222222                   1.032057  
1                    0.166667                  -0.124958  
2                    0.111111                   0.337848  
3                    0.083333                   0.106445  
4                    0.194444                   1.263460