In [1]:
import numpy as np
import math
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

def sigmoid (x):
    return 1/(1+np.exp(-x))
class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs)+self.bias
        return sigmoid(total)

In [2]:
"""Задание 1.1.3 Р/т №7"""

class TripleInputNeuralNetwork:
    def __init__(self):
        weights = np.array([0.5, 0.5, 0.5])
        bias =0
        self.h1 = Neuron(weights=weights, bias=bias)
        self.h2 = Neuron(weights=weights, bias=bias)
        self.h3 = Neuron(weights=weights, bias=bias)
        self.o1 = Neuron(weights=weights, bias=bias)
    def feedforwards(self, x):
        out_h1=self.h1.feedforward(x)
        out_h2=self.h2.feedforward(x)
        out_h3=self.h3.feedforward(x)
        out_o1=self.o1.feedforward(np.array([out_h1, out_h2, out_h3]))
        return out_o1

network = TripleInputNeuralNetwork()
x=np.array([2,3,4])
print(network.feedforwards(x))

class DoubleInputNeuralNetwork:
    def __init__(self):
        weights = np.array([0,1])
        bias =0
        self.h1 = Neuron(weights=weights, bias=bias)
        self.h2 = Neuron(weights=weights, bias=bias)
        self.o1 = Neuron(weights=weights, bias=bias)
        self.o2 = Neuron(weights=weights, bias=bias)
    def feedforwards(self, x):
        out_h1=self.h1.feedforward(x)
        out_h2=self.h2.feedforward(x)
        out_o1=self.o1.feedforward(np.array([out_h1, out_h2]))
        out_o2=self.o2.feedforward(np.array([out_h1, out_h2]))
        return out_o1, out_o2

network = DoubleInputNeuralNetwork()
x=np.array([2,3])
print(network.feedforwards(x))

0.8151036049051821
(0.7216325609518421, 0.7216325609518421)


In [3]:
"""Задание 1.1.4 Р/т №7"""

def tanh (x):
    return math.tanh(x)
class TanhNeuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs)+self.bias
        return tanh(total)
class TanhTripleInputNeuralNetwork:
    def __init__(self):
        weights = np.array([0.5, 0.5, 0.5])
        bias =0
        self.h1 = TanhNeuron(weights=weights, bias=bias)
        self.h2 = TanhNeuron(weights=weights, bias=bias)
        self.h3 = TanhNeuron(weights=weights, bias=bias)
        self.o1 = TanhNeuron(weights=weights, bias=bias)
    def feedforwards(self, x):
        out_h1=self.h1.feedforward(x)
        out_h2=self.h2.feedforward(x)
        out_h3=self.h3.feedforward(x)
        out_o1=self.o1.feedforward(np.array([out_h1, out_h2, out_h3]))
        return out_o1
    
network1 = TanhTripleInputNeuralNetwork()
x=np.array([2,3,4])
print(network1.feedforwards(x))

def relumax (x):
    return max(0, x)
class RelUNeuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs)+self.bias
        return tanh(total)
class ReLUTripleInputNeuralNetwork:
    def __init__(self):
        weights = np.array([0.5, 0.5, 0.5])
        bias =0
        self.h1 = RelUNeuron(weights=weights, bias=bias)
        self.h2 = RelUNeuron(weights=weights, bias=bias)
        self.h3 = RelUNeuron(weights=weights, bias=bias)
        self.o1 = RelUNeuron(weights=weights, bias=bias)
    def feedforwards(self, x):
        out_h1=self.h1.feedforward(x)
        out_h2=self.h2.feedforward(x)
        out_h3=self.h3.feedforward(x)
        out_o1=self.o1.feedforward(np.array([out_h1, out_h2, out_h3]))
        return out_o1

network2 = ReLUTripleInputNeuralNetwork()
y=np.array([2,3,4])
print(network2.feedforwards(y))

0.9050813365686774
0.9050813365686774


In [4]:
"""Задание 1.3.1 Р/т №7"""

from sklearn.datasets import load_iris
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
import numpy as np
iris = load_iris()
dataframe = pd.read_csv("https://raw.githubusercontent.com/AnnaShestova/salary-years-simple-linear-regression/master/Salary_Data.csv")
exp = dataframe.iloc[:, :-1].values
salary = dataframe.iloc[:, 1].values

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(iris.data, iris.target, test_size=0.20, random_state=123)
mlp_classifier = MLPClassifier(random_state=123)
mlp_classifier.fit(X_train, Y_train)
Y_preds = mlp_classifier.predict(X_test)
print(Y_preds[:15])
print(Y_test[:15])
print(f'Test Accuracy: {mlp_classifier.score(X_test, Y_test)}')
print(f'Training Accuracy: {mlp_classifier.score(X_train, Y_train)}')
print(f'Loss : {mlp_classifier.loss_}')
print(f'Number of coefs : {len(mlp_classifier.coefs_)}')
print(f'Number of Intercept : {len(mlp_classifier.intercepts_)}')
print(f'Number of Iterations for Which Estimator Ran : {mlp_classifier.n_iter_}')
print(f'Name of Output Layer Activation Function : {mlp_classifier.out_activation_}')

[1 2 2 1 0 2 1 0 0 1 2 0 1 2 2]
[1 2 2 1 0 2 1 0 0 1 2 0 1 2 2]
Test Accuracy: 0.9666666666666667
Training Accuracy: 0.975
Loss : 0.3012607394074939
Number of coefs : 2
Number of Intercept : 2
Number of Iterations for Which Estimator Ran : 200
Name of Output Layer Activation Function : softmax


c:\Users\Денис\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [8]:
X_train, X_test, Y_train, Y_test=train_test_split(exp, salary, test_size=0.20, random_state=123)
mlp_regressor = MLPRegressor(random_state=123)
#from sklearn.linear_model import LinearRegression
#mlp_regressor = LinearRegression() 
mlp_regressor.fit(X_train, Y_train)
Y_preds = mlp_regressor.predict(X_test)
print(Y_preds[:10])
print(Y_test[:10])
print(f'Test R^2 Accuracy: {mlp_regressor.score(X_test, Y_test)}')
print(f'Training R^2 Accuracy: {mlp_regressor.score(X_train, Y_train)}')
print(f'Loss : {mlp_regressor.loss_}')
print(f'Number of coefs : {len(mlp_regressor.coefs_)}')
print(f'Number of Intercept : {len(mlp_regressor.intercepts_)}')
print(f'Number of Iterations for Which Estimator Ran : {mlp_regressor.n_iter_}')
print(f'Name of Output Layer Activation Function : {mlp_regressor.out_activation_}')

[20.26234628 55.2781752  18.82135812 50.48274487 20.26234628 50.9622879 ]
[ 54445. 121872.  56642. 116969.  64445. 112635.]
Test R^2 Accuracy: -8.796447137437891
Training R^2 Accuracy: -8.260600732856043
Loss : 2988058032.1601596
Number of coefs : 2
Number of Intercept : 2
Number of Iterations for Which Estimator Ran : 200
Name of Output Layer Activation Function : identity


c:\Users\Денис\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
