In [6]:
"""Задание 1.3.1 Р/т №2"""
import numpy as np

array = np.zeros((10,10))
array[::2, ::2] = 1
array[1::2, 1::2] = 1
print(array)

[[1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


In [9]:
"""Задание 1.3.2 Р/т №2"""
import numpy as np

array = np.zeros((5, 5))
array[::, ::] = np.arange(0, 5)
print(array)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [10]:
"""Задание 1.3.3 Р/т №2"""
import numpy as np

array = np.random.random((3, 3, 3))
print(array)

[[[0.42857248 0.41996726 0.61864638]
  [0.51677587 0.85608067 0.40513955]
  [0.10267609 0.42202458 0.98272868]]

 [[0.61193113 0.14612973 0.12857492]
  [0.66331751 0.49679069 0.74023934]
  [0.86611741 0.7761596  0.97241135]]

 [[0.07831752 0.76392549 0.69915404]
  [0.99416972 0.02096552 0.65550998]
  [0.94914803 0.5320406  0.5024433 ]]]


In [12]:
"""Задание 1.3.4 Р/т №2"""
import numpy as np

array = np.zeros((5, 5))
array[0, ::] = 1
array[::, 0] = 1
array[::, -1] = 1
array[-1, ::] = 1
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
"""Задание 1.3.5 Р/т №2"""
import numpy as np

array = np.array([3, 5, 2, 7, 1, 4, 6])
print(np.sort(array)[::-1])

[7 6 5 4 3 2 1]


In [16]:
"""Задание 1.3.5 Р/т №2"""
import numpy as np

array = np.zeros((5, 4))

print(array.shape, '\n',array.size, '\n',array.ndim)

(5, 4) 
 20 
 2
